/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * adgk.java
 *
 * Created on 25 Jan, 2012, 9:23:24 PM
 */

package sankeladder;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JApplet;

/**
 *
 * @author SONY
 */
public class Snake_Ladder_Applet extends JApplet {


    /** Creates new form adgk */
    public Snake_Ladder_Applet() {
        System.out.println("Class COMPILATION STARTS");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(306, 25));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Snap ITC", 3, 12));
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Preset Board");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.ipady = 71;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 180, 10);
        jPanel1.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Snap ITC", 3, 12));
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Make My Board");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.ipady = 71;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 182, 10);
        jPanel1.add(jButton2, gridBagConstraints);

        jLabel10.setDisabledIcon(new javax.swing.ImageIcon("D:\\Studies\\2nd Year\\4th Sem\\Software\\Sanke & Ladder\\snake_ladder_top_panel1.jpg")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel10, org.jdesktop.beansbinding.ELProperty.create("${disabledIcon}"), jLabel10, org.jdesktop.beansbinding.BeanProperty.create("icon"));
        bindingGroup.addBinding(binding);

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 62, 46, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(51, 0, 204));
        jLabel2.setFont(new java.awt.Font("Snap ITC", 3, 18));
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Choose Size of Board");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 156;
        gridBagConstraints.insets = new java.awt.Insets(130, 0, 120, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        jComboBox1.setBackground(new java.awt.Color(255, 51, 51));
        jComboBox1.setFont(new java.awt.Font("Snap ITC", 3, 12));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(69, 80, 190), new java.awt.Color(51, 0, 51), new java.awt.Color(102, 0, 102)));
        jComboBox1.setOpaque(false);
        jComboBox1.setPreferredSize(new java.awt.Dimension(37, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 157;
        gridBagConstraints.insets = new java.awt.Insets(130, 2, 120, 0);
        jPanel2.add(jComboBox1, gridBagConstraints);

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Snap ITC", 3, 12));
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("PLAY>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 155;
        gridBagConstraints.insets = new java.awt.Insets(130, 0, 120, 163);
        jPanel2.add(jButton3, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));

        jLabel3.setBackground(new java.awt.Color(102, 255, 51));
        jLabel3.setFont(new java.awt.Font("Snap ITC", 3, 24));
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Player Names");

        jLabel4.setBackground(new java.awt.Color(102, 255, 51));
        jLabel4.setFont(new java.awt.Font("Snap ITC", 3, 14));
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Player 1");

        jTextField1.setFont(new java.awt.Font("Segoe Script", 3, 14));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 255, 51));
        jLabel5.setFont(new java.awt.Font("Snap ITC", 3, 14));
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Player 2");

        jTextField2.setFont(new java.awt.Font("Segoe Script", 3, 14));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 255, 51));
        jLabel6.setFont(new java.awt.Font("Snap ITC", 3, 14));
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Player 3");

        jTextField3.setFont(new java.awt.Font("Segoe Script", 3, 14));

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setFont(new java.awt.Font("Snap ITC", 3, 12));
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("Go Go Go");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("RED");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("BLUE");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("YELLOW");

        jLabel1.setBackground(new java.awt.Color(51, 0, 204));
        jLabel1.setFont(new java.awt.Font("Snap ITC", 3, 24));
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon("D:\\Studies\\2nd Year\\4th Sem\\Software\\Sanke & Ladder\\snake_ladder_top_panel1.jpg")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${disabledIcon}"), jLabel1, org.jdesktop.beansbinding.BeanProperty.create("icon"));
        bindingGroup.addBinding(binding);

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(177, 177, 177))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel3)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(53, 53, 53)
                .addComponent(jButton4)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setVisible(false);
        jPanel2.setVisible(false);

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-639)/2, (screenSize.height-669)/2, 639, 669);
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jLabel1.setVisible(true);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // TODO add your handling code here:
            //applet_version2 av = new applet_version2();
            int []snakes = new int[65];
            int []ladders = new int[65];
            FileInputStream fstream;
            fstream = new FileInputStream("Player Info.txt");
            DataInputStream in = new DataInputStream(fstream);
            BufferedReader br = new BufferedReader(new InputStreamReader(in));
            String strLine=null;
            if ((strLine = br.readLine()) != null)
            {

                for(int a=0;a<65;a++)
                {
                    snakes[a]=-1;
                    ladders[a]=-1;
                }
                snakes[63]=27;
                snakes[49]=4;
                snakes[42]=25;
                snakes[24]=7;
                ladders[5]=34;
                ladders[29]=53;
                ladders[46]=62;
                ladders[14]=39;
                applet_version3 av = new applet_version3();
                av.snake_and_ladder(8,Integer.parseInt(strLine),snakes,ladders);
                 //av.snake_ladder_image(av.c1, snakes, ladders, av.c1.size);
                 System.out.println("Image loaded in adgk");
            }
            //av.snake_and_ladder(jComboBox1.getSelectedIndex() + 5);
        } catch (Exception ex) {
            Logger.getLogger(adgk.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            //applet_version2 av = new applet_version2();
            FileInputStream fstream;
            fstream = new FileInputStream("Player Info.txt");
            DataInputStream in = new DataInputStream(fstream);
            BufferedReader br = new BufferedReader(new InputStreamReader(in));
            String strLine=null;
            if ((strLine = br.readLine()) != null)
            {
                Design_Board2 db = new Design_Board2();
                db.design_board(jComboBox1.getSelectedIndex() + 5 ,Integer.parseInt(strLine));
            }
        } catch (IOException ex) {
            Logger.getLogger(adgk.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jPanel3.setVisible(true);
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(jTextField1.getText().equals("") || "Enter Atleast 1 Player Name".equals(jTextField1.getText()))
        {
            //System.out.println("28942");
            jTextField1.setText("Enter Atleast 1 Player Name");
            return;
        }
        else
        {
            //System.out.println("adfgh");
            FileWriter fstream = null;
            try{
                fstream = new FileWriter("Player Info.txt");
                BufferedWriter out = new BufferedWriter(fstream);
                if(jTextField2.getText().equals(""))
                {
                    out.write("1");
                    out.newLine();
                    out.write(jTextField1.getText());
                    out.newLine();
                }
                else
                if(jTextField3.getText().equals(""))
                {
                    out.write("2");
                    out.newLine();
                    out.write(jTextField1.getText());
                    out.newLine();
                    out.write(jTextField2.getText());
                    out.newLine();
                }
                else
                {
                    out.write("3");
                    out.newLine();
                    out.write(jTextField1.getText());
                    out.newLine();
                    out.write(jTextField2.getText());
                    out.newLine();
                    out.write(jTextField3.getText());
                    out.newLine();
                }
                out.close();

                jPanel1.setVisible(true);
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
            } catch (Exception ex) {
                Logger.getLogger(adgk.class.getName()).log(Level.SEVERE, null, ex);
            }


}
    }

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
         if("Enter Atleast 1 Player Name".equals(jTextField1.getText()))
            jTextField1.setText("");
    }

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jPanel3.setVisible(true);
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
    }

    /**
    * @param args the command line arguments
    */
  //  public static void main(String args[]) {
    public static void design()
    {
        System.out.println("DESIGN COMPILATION STARTS");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Snake_Ladder_Applet().setVisible(true);
            }
        });
        System.out.println("DESIGN COMPILATION Ends");
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration

}
